/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fvsosp.telas;

/**
 *
 * @author ADRIANO
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Principal
     */
    public TelaPrincipal() {
        initComponents();
        //setExtendedState( MAXIMIZED_BOTH ); ;   //( iniciar tela cheia )
        setTitle("OSBiblio");
        setLocationRelativeTo(null);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        BarradeMenuPrincipal = new javax.swing.JMenuBar();
        menuCadastrado = new javax.swing.JMenu();
        itemCadAcervo = new javax.swing.JMenuItem();
        itemCadAluno = new javax.swing.JMenuItem();
        itemCadAutor = new javax.swing.JMenuItem();
        itemCadBiblioteca = new javax.swing.JMenuItem();
        itemCadGrupoLeitores = new javax.swing.JMenuItem();
        itemCadSessao = new javax.swing.JMenuItem();
        itemCadUsuario = new javax.swing.JMenuItem();
        itemEmprestar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenu();
        itemConsultarAcervo = new javax.swing.JMenuItem();
        itemRelatorioUsuario = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        itemRelatorioFinanceiro = new javax.swing.JMenuItem();
        itemRelatorioEmprestimo = new javax.swing.JMenuItem();
        itemRelatorioCatalogacao = new javax.swing.JMenuItem();
        ItemSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fvsosp/imagens/Logo da faculdade.jpg"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(59, 89, 159));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuário:Nome do Usuário que esta logado");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Versão: 1.0");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fone: 0000-0000");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(49, 49, 49)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(59, 89, 159));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        BarradeMenuPrincipal.setBackground(new java.awt.Color(51, 51, 255));
        BarradeMenuPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        menuCadastrado.setText("Cadastro");
        menuCadastrado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuCadastrado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        itemCadAcervo.setText("Acervo");
        itemCadAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadAcervoActionPerformed(evt);
            }
        });
        menuCadastrado.add(itemCadAcervo);

        itemCadAluno.setText("Aluno");
        itemCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadAlunoActionPerformed(evt);
            }
        });
        menuCadastrado.add(itemCadAluno);

        itemCadAutor.setText("Autor");
        itemCadAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadAutorActionPerformed(evt);
            }
        });
        menuCadastrado.add(itemCadAutor);

        itemCadBiblioteca.setText("Biblioteca");
        itemCadBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadBibliotecaActionPerformed(evt);
            }
        });
        menuCadastrado.add(itemCadBiblioteca);

        itemCadGrupoLeitores.setText("Grupo Leitores");
        itemCadGrupoLeitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadGrupoLeitoresActionPerformed(evt);
            }
        });
        menuCadastrado.add(itemCadGrupoLeitores);

        itemCadSessao.setText("Sessão");
        itemCadSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadSessaoActionPerformed(evt);
            }
        });
        menuCadastrado.add(itemCadSessao);

        itemCadUsuario.setText("Usuário");
        itemCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadUsuarioActionPerformed(evt);
            }
        });
        menuCadastrado.add(itemCadUsuario);

        BarradeMenuPrincipal.add(menuCadastrado);

        itemEmprestar.setText("Emprestimos");

        jMenuItem1.setText("Emprestar");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        itemEmprestar.add(jMenuItem1);

        BarradeMenuPrincipal.add(itemEmprestar);

        menuConsulta.setText("Consulta");

        itemConsultarAcervo.setText("Acervo");
        menuConsulta.add(itemConsultarAcervo);

        BarradeMenuPrincipal.add(menuConsulta);

        itemRelatorioUsuario.setText("Relatórios");

        jMenuItem3.setText("Usuário");
        itemRelatorioUsuario.add(jMenuItem3);

        itemRelatorioFinanceiro.setText("Financeiro");
        itemRelatorioUsuario.add(itemRelatorioFinanceiro);

        itemRelatorioEmprestimo.setText("Emprestimo");
        itemRelatorioUsuario.add(itemRelatorioEmprestimo);

        itemRelatorioCatalogacao.setText("Catalogação");
        itemRelatorioUsuario.add(itemRelatorioCatalogacao);

        BarradeMenuPrincipal.add(itemRelatorioUsuario);

        ItemSair.setText("Sair");
        ItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemSairActionPerformed(evt);
            }
        });
        BarradeMenuPrincipal.add(ItemSair);

        setJMenuBar(BarradeMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void ItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemSairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_ItemSairActionPerformed

    private void itemCadAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadAcervoActionPerformed
        // Instancie sua Tela
    }//GEN-LAST:event_itemCadAcervoActionPerformed

    private void itemCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadAlunoActionPerformed
        // Instancie sua Tela
    }//GEN-LAST:event_itemCadAlunoActionPerformed

    private void itemCadAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadAutorActionPerformed
        // Instancie sua Tela
    }//GEN-LAST:event_itemCadAutorActionPerformed

    private void itemCadBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadBibliotecaActionPerformed
        new TelaCadastroBiblioteca().setVisible(true);
    }//GEN-LAST:event_itemCadBibliotecaActionPerformed

    private void itemCadGrupoLeitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadGrupoLeitoresActionPerformed
        // Instancie sua Tela
    }//GEN-LAST:event_itemCadGrupoLeitoresActionPerformed

    private void itemCadSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadSessaoActionPerformed
        new TelaCadastroSessao().setVisible(true);
    }//GEN-LAST:event_itemCadSessaoActionPerformed

    private void itemCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadUsuarioActionPerformed
        // Instancie sua Tela
    }//GEN-LAST:event_itemCadUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarradeMenuPrincipal;
    private javax.swing.JMenu ItemSair;
    private javax.swing.JMenuItem itemCadAcervo;
    private javax.swing.JMenuItem itemCadAluno;
    private javax.swing.JMenuItem itemCadAutor;
    private javax.swing.JMenuItem itemCadBiblioteca;
    private javax.swing.JMenuItem itemCadGrupoLeitores;
    private javax.swing.JMenuItem itemCadSessao;
    private javax.swing.JMenuItem itemCadUsuario;
    private javax.swing.JMenuItem itemConsultarAcervo;
    private javax.swing.JMenu itemEmprestar;
    private javax.swing.JMenuItem itemRelatorioCatalogacao;
    private javax.swing.JMenuItem itemRelatorioEmprestimo;
    private javax.swing.JMenuItem itemRelatorioFinanceiro;
    private javax.swing.JMenu itemRelatorioUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenu menuCadastrado;
    private javax.swing.JMenu menuConsulta;
    // End of variables declaration//GEN-END:variables
}