/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fvsosp.telas;

import fvsosp.acervo.*;
import fvsosp.autor.Autor;
import fvsosp.autor.AutorRN;
import fvsosp.biblioteca.Biblioteca;
import fvsosp.biblioteca.BibliotecaRN;
import fvsosp.editora.Editora;
import fvsosp.editora.EditoraRN;
import fvsosp.especificacoes.EspecificacoesTecnicas;
import fvsosp.especificacoes.EspecificacoesTecnicasRN;
import fvsosp.exemplar.Exemplar;
import fvsosp.idioma.Idioma;
import fvsosp.idioma.IdiomaRN;
import fvsosp.palavraschaves.PalavrasChaves;
import fvsosp.sessao.Sessao;
import fvsosp.sessao.SessaoRN;
import fvsosp.tipoitem.TipoItem;
import fvsosp.tipoitem.TipoItemRN;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author TÚLIO
 */
public class TelaCadastroAcervo extends javax.swing.JDialog {

    Acervo acervo;
    AcervoRN acervoRN = new AcervoRN();
    Exemplar exemplar;

    /**
     * Creates new form TelaCadastroAcervo
     */
    public TelaCadastroAcervo() {
        initComponents();
        this.setTitle("OSBiblio - Acervo");
        this.setLocationRelativeTo(null);
        //btRemover.setEnabled(false);
        setModal(true);
        preencheAutor();
        preencheBiblioteca();
        preencheEditora();
        preencheIdioma();
        preencheSessao();
        preencheTipoItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btPesquisar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        tbLeitor = new javax.swing.JTabbedPane();
        pn1 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        tfTitulo = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tfSubTitulo = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tfEdicao = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        tfVolume = new javax.swing.JTextField();
        tfInformacoesAdicionais = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        tfLocalizacao = new javax.swing.JTextField();
        tffAnoEdicao = new javax.swing.JFormattedTextField();
        tfIsbn1 = new javax.swing.JTextField();
        pn3 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        tfPalavrasChaves = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPesquisa = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        tfExemplar = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        tfTombo = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        tfAcabamentoCapa = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tfAcabamentoMiolo = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        tfPaginas = new javax.swing.JTextField();
        tfPeso = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbBiblioteca = new javax.swing.JComboBox();
        cbEditora = new javax.swing.JComboBox();
        cbIdioma = new javax.swing.JComboBox();
        cbSessao = new javax.swing.JComboBox();
        cbAutor = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cbTipoItem = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(59, 89, 152));
        jPanel3.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Acervo");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(0, 0, 170, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(432, 177));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fvsosp/imagens/procurar_1.png"))); // NOI18N
        btPesquisar.setToolTipText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        jPanel2.add(btPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 37, 33));

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fvsosp/imagens/SA.png"))); // NOI18N
        btSair.setToolTipText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jPanel2.add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        btRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fvsosp/imagens/remove_1.png"))); // NOI18N
        btRemover.setToolTipText("Excluir");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });
        jPanel2.add(btRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 37, 33));

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fvsosp/imagens/save_1.png"))); // NOI18N
        btSalvar.setToolTipText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 40, 33));

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fvsosp/imagens/novo_1.png"))); // NOI18N
        btNovo.setToolTipText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jPanel2.add(btNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 42, 33));

        tbLeitor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLeitorMouseClicked(evt);
            }
        });

        pn1.setBackground(new java.awt.Color(255, 255, 255));
        pn1.setMinimumSize(new java.awt.Dimension(430, 300));
        pn1.setPreferredSize(new java.awt.Dimension(430, 300));
        pn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel31.setText("Titulo da Obra.:");
        pn1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 29));

        tfTitulo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfTitulo.setToolTipText("Digite aqui o título da obra");
        pn1.add(tfTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 420, -1));

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel25.setText("Subtitulo da Obra.:");
        pn1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 29));

        tfSubTitulo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfSubTitulo.setToolTipText("Digite aqui o subtítulo da obra");
        pn1.add(tfSubTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 420, -1));

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel28.setText("ISBN.:");
        pn1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 29));

        jLabel32.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel32.setText("Edição.:");
        pn1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 29));

        jLabel33.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel33.setText("Ano edição.:");
        pn1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, 29));

        tfEdicao.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfEdicao.setToolTipText("Digite aqui a edição da obra");
        pn1.add(tfEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 170, -1));

        jLabel41.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel41.setText("Volume.:");
        pn1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, 29));

        tfVolume.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfVolume.setToolTipText("Digite aqui o ISBN da obra");
        pn1.add(tfVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 170, -1));

        tfInformacoesAdicionais.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfInformacoesAdicionais.setToolTipText("Digite aqui as informações adicionais");
        pn1.add(tfInformacoesAdicionais, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 170, -1));

        jLabel42.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel42.setText("Informações Adicionais.:");
        pn1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 29));

        jLabel43.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel43.setText("Localização.:");
        pn1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, 29));

        tfLocalizacao.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfLocalizacao.setToolTipText("Digite aqui a localização");
        pn1.add(tfLocalizacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 170, -1));

        tffAnoEdicao.setToolTipText("Digite aqui o ano de edição");
        pn1.add(tffAnoEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 170, 20));

        tfIsbn1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfIsbn1.setToolTipText("Digite aqui o ISBN da obra");
        pn1.add(tfIsbn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, -1));

        tbLeitor.addTab("Obra", pn1);

        pn3.setBackground(new java.awt.Color(255, 255, 255));
        pn3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel39.setText("Palavras Chaves.:");
        pn3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 29));

        tfPalavrasChaves.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfPalavrasChaves.setToolTipText("Digite aqui as palavras chaves");
        tfPalavrasChaves.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPalavrasChavesKeyReleased(evt);
            }
        });
        pn3.add(tfPalavrasChaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 380, -1));

        tbPesquisa.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tbPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Palavras Chaves"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPesquisa.setRowSelectionAllowed(false);
        tbPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPesquisaMouseClicked(evt);
            }
        });
        tbPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbPesquisaKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbPesquisa);
        tbPesquisa.getColumnModel().getColumn(0).setResizable(false);

        pn3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 380, 140));

        tbLeitor.addTab("Palavras Chaves", pn3);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel36.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel36.setText("Tombo.:");

        tfExemplar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfExemplar.setToolTipText("Digite aqui o número do exemplar");

        jLabel37.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel37.setText("Número do Exemplar.:");

        tfTombo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfTombo.setToolTipText("Digite aqui o tombo");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(tfExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(tfTombo, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(tfTombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tfExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        tbLeitor.addTab("Exemplar", jPanel6);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel34.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel34.setText("Acabamento da Capa.:");

        tfAcabamentoCapa.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfAcabamentoCapa.setToolTipText("Digite aqui o acabamento da capa");

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel27.setText("Acabamento do Miolo.:");

        tfAcabamentoMiolo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfAcabamentoMiolo.setToolTipText("Digite aqui o acabamento do miolo");

        jLabel35.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel35.setText("Peso.:");

        jLabel44.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel44.setText("Número de Páginas.:");

        tfPaginas.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfPaginas.setToolTipText("Digite aqui o número de páginas");

        tfPeso.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfPeso.setToolTipText("Digite aqui o peso");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addComponent(tfPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 17, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel34)
                        .addComponent(tfAcabamentoCapa, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27)
                        .addComponent(tfAcabamentoMiolo, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 18, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(1, 1, 1)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfAcabamentoCapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(1, 1, 1)
                    .addComponent(tfAcabamentoMiolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 174, Short.MAX_VALUE)))
        );

        tbLeitor.addTab("Especificações Técnicas", jPanel5);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Biblioteca.:");

        jLabel2.setText("Editora.:");

        jLabel4.setText("Idioma.:");

        jLabel5.setText("Sessão.:");

        jLabel6.setText("Tipo Item.:");

        cbBiblioteca.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbBiblioteca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));

        cbEditora.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbEditora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));

        cbIdioma.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbIdioma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));

        cbSessao.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbSessao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));

        cbAutor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbAutor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));

        jLabel7.setText("Autor.:");

        cbTipoItem.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbTipoItem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cbAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(cbIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addComponent(cbSessao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbTipoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        tbLeitor.addTab("Outros", jPanel4);

        jPanel2.add(tbLeitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 460, 310));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        List<Acervo> lista = null;
        if (tfTitulo.getText() != null) {
            lista = acervoRN.pesquisarTitulodaObra(tfTitulo.getText());
        } else {
            lista = acervoRN.listar();
        }
        AcervoTableModel atm = new AcervoTableModel(lista);
        Object o = TelaPesquisa.exibeTela(atm, "Acervo");
        acervo = new Acervo();
        if (o != null) {
            short id = (short) o;
            acervo = acervoRN.pesquisarCodigo(id);
            tfTitulo.setText(acervo.getTituloObra().toString());
            tfSubTitulo.setText(acervo.getSubtituloObra().toString());
            tfVolume.setText(acervo.getIsbn().toString());
            tfVolume.setText(acervo.getVolume().toString());
            tfEdicao.setText(acervo.getEdicao().toString());
            tffAnoEdicao.setText(String.valueOf(acervo.getAnoEdicao()));
            tfInformacoesAdicionais.setText(acervo.getInformacoesAdicionais().toString());
            tfLocalizacao.setText(acervo.getLocalizacao());
            btRemover.setEnabled(true);
            if (acervo.getAutor() != null) {
                cbAutor.setSelectedItem(acervo.getAutor());
            } else {
                cbAutor.setSelectedIndex(0);
            }
            if (acervo.getBiblioteca() != null) {
                cbBiblioteca.setSelectedItem(acervo.getBiblioteca());
            } else {
                cbBiblioteca.setSelectedIndex(0);
            }
            if (acervo.getEditora() != null) {
                cbEditora.setSelectedItem(acervo.getEditora());
            } else {
                cbEditora.setSelectedIndex(0);
            }
            if (acervo.getIdioma() != null) {
                cbIdioma.setSelectedItem(acervo.getIdioma());
            } else {
                cbIdioma.setSelectedIndex(0);
            }
            if (acervo.getSessao() != null) {
                cbSessao.setSelectedItem(acervo.getSessao());
            } else {
                cbSessao.setSelectedIndex(0);
            }
            if (acervo.getTipoItem() != null) {
                cbTipoItem.setSelectedItem(acervo.getTipoItem());
            } else {
                cbTipoItem.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btSairActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        if (acervo != null) {
            if (acervo.getIdAcervo() != 0) {
                if (JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o acervo " + acervo.getTituloObra()
                        + "?", "OSBiblio", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.YES_OPTION) {
                    if (acervoRN.remover(acervo)) {
                        JOptionPane.showMessageDialog(rootPane, "Acervo " + acervo.getTituloObra()
                                + ", excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Não foi possível excluir o acervo "
                                + acervo.getTituloObra(),
                                "Erro ao Excluir", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
        limparCampos();
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        if (acervo == null) {
            acervo = new Acervo();
        }

        if (!tffAnoEdicao.getText().isEmpty()) {
            Calendar data = Calendar.getInstance();
            if (Long.parseLong(tffAnoEdicao.getText()) > data.get(Calendar.YEAR)) {
                JOptionPane.showMessageDialog(null, "Não é possível inserir um ano de edição superior ao ano atual. ");
            } else
                acervo.setAnoEdicao(Short.parseShort(tffAnoEdicao.getText()));
        }
        acervo.setTituloObra(tfTitulo.getText());
        acervo.setSubtituloObra(tfSubTitulo.getText());
        acervo.setIsbn(tfVolume.getText());
        acervo.setVolume(tfVolume.getText());
        acervo.setEdicao(tfEdicao.getText());
        acervo.setInformacoesAdicionais(tfInformacoesAdicionais.getText());
        acervo.setLocalizacao(tfLocalizacao.getText());
        if (!tfTombo.getText().isEmpty() && !tfExemplar.getText().isEmpty()) {
            exemplar.setTombo(Short.parseShort(tfTombo.getText()));
            exemplar.setExemplar(Short.parseShort(tfExemplar.getText()));
            List<Exemplar> exemplares = new ArrayList<>();
            exemplares.add(exemplar);
            acervo.setExemplares(exemplares);
        }
        if ((cbAutor.getSelectedIndex() > 0) && (cbBiblioteca.getSelectedIndex() > 0) && (cbEditora.getSelectedIndex() > 0)
                && (cbIdioma.getSelectedIndex() > 0) && (cbSessao.getSelectedIndex() > 0) && (cbTipoItem.getSelectedIndex() > 0)) {
            Autor autor = (Autor) cbAutor.getSelectedItem();
            acervo.setAutor(autor);
            Biblioteca biblioteca = (Biblioteca) cbBiblioteca.getSelectedItem();
            acervo.setBiblioteca(biblioteca);
            Editora editora = (Editora) cbEditora.getSelectedItem();
            acervo.setEditora(editora);
            Idioma idioma = (Idioma) cbIdioma.getSelectedItem();
            acervo.setIdioma(idioma);
            Sessao sessao = (Sessao) cbSessao.getSelectedItem();
            acervo.setSessao(sessao);
            TipoItem tipoitem = (TipoItem) cbTipoItem.getSelectedItem();
            acervo.setTipoItem(tipoitem);
        } else {
            acervo.setAutor(null);
            acervo.setBiblioteca(null);
            acervo.setEditora(null);
            acervo.setIdioma(null);
            acervo.setSessao(null);
            acervo.setTipoItem(null);
        }

        int tdAcervo = acervo.getIdAcervo();
        if (acervoRN.salvar(acervo)) {
            if (tdAcervo == 0) {
                JOptionPane.showMessageDialog(rootPane, "Acervo " + acervo.getTituloObra() + ", cadastrado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Acervo " + acervo.getTituloObra()
                        + ", alterado com sucesso!");
            }
            limparCampos();
            btRemover.setEnabled(false);
        }
    }

    private void preencheAutor() {
        AutorRN autRN = new AutorRN();
        List<Autor> autores = autRN.listar();
        for (Autor autor : autores) {
            cbAutor.addItem(autor);
        }
    }

    private void preencheBiblioteca() {
        BibliotecaRN bibRN = new BibliotecaRN();
        List<Biblioteca> bibliotecas = bibRN.listar();
        for (Biblioteca biblioteca : bibliotecas) {
            cbBiblioteca.addItem(biblioteca);
        }
    }

    private void preencheEditora() {
        EditoraRN edtRN = new EditoraRN();
        List<Editora> editoras = edtRN.listar();
        for (Editora editora : editoras) {
            cbEditora.addItem(editora);
        }
    }

    private void preencheIdioma() {
        IdiomaRN idRN = new IdiomaRN();
        List<Idioma> idiomas = idRN.listar();
        for (Idioma idioma : idiomas) {
            cbIdioma.addItem(idioma);
        }
    }

    private void preencheSessao() {
        SessaoRN sesRN = new SessaoRN();
        List<Sessao> sessoes = sesRN.listar();
        for (Sessao sessao : sessoes) {
            cbSessao.addItem(sessao);
        }
    }

    private void preencheTipoItem() {
        TipoItemRN tipRN = new TipoItemRN();
        List<TipoItem> tipoitens = tipRN.listar();
        for (TipoItem tipo : tipoitens) {
            cbTipoItem.addItem(tipo);
        }
    }

    public void limparCampos() {
        tfTitulo.setText("");
        tfSubTitulo.setText("");
        tfVolume.setText("");
        tfVolume.setText("");
        tfEdicao.setText("");
        tffAnoEdicao.setText("");
        tfInformacoesAdicionais.setText("");
        tfLocalizacao.setText("");
        cbAutor.setSelectedIndex(0);
        cbBiblioteca.setSelectedIndex(0);
        cbEditora.setSelectedIndex(0);
        cbIdioma.setSelectedIndex(0);
        cbSessao.setSelectedIndex(0);
        cbTipoItem.setSelectedIndex(0);
        tfPalavrasChaves.setText("");
        tfTombo.setText("");
        tfExemplar.setText("");
        tfAcabamentoCapa.setText("");
        tfAcabamentoMiolo.setText("");
        tfPaginas.setText("");
        tfPeso.setText("");
        acervo = null;
        tfTitulo.requestFocus();
        btRemover.setEnabled(false);
    }//GEN-LAST:event_btSalvarActionPerformed
    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_btNovoActionPerformed

    private void tbPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbPesquisaKeyPressed
        // TODO add your handling code here:
        //if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        //    btSelecionarActionPerformed(null);
        // }
    }//GEN-LAST:event_tbPesquisaKeyPressed

    private void tbPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPesquisaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbPesquisaMouseClicked

    private void tfPalavrasChavesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPalavrasChavesKeyReleased
        /*PalavrasChaves palavras = new PalavrasChaves();
         tfPalavrasChaves.setText(palavras.getDescricao());*/
    }//GEN-LAST:event_tfPalavrasChavesKeyReleased

    private void tbLeitorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLeitorMouseClicked
    }//GEN-LAST:event_tbLeitorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAcervo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAcervo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAcervo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAcervo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroAcervo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbAutor;
    private javax.swing.JComboBox cbBiblioteca;
    private javax.swing.JComboBox cbEditora;
    private javax.swing.JComboBox cbIdioma;
    private javax.swing.JComboBox cbSessao;
    private javax.swing.JComboBox cbTipoItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pn1;
    private javax.swing.JPanel pn3;
    private javax.swing.JTabbedPane tbLeitor;
    private javax.swing.JTable tbPesquisa;
    private javax.swing.JTextField tfAcabamentoCapa;
    private javax.swing.JTextField tfAcabamentoMiolo;
    private javax.swing.JTextField tfEdicao;
    private javax.swing.JTextField tfExemplar;
    private javax.swing.JTextField tfInformacoesAdicionais;
    private javax.swing.JTextField tfIsbn1;
    private javax.swing.JTextField tfLocalizacao;
    private javax.swing.JTextField tfPaginas;
    private javax.swing.JTextField tfPalavrasChaves;
    private javax.swing.JTextField tfPeso;
    private javax.swing.JTextField tfSubTitulo;
    private javax.swing.JTextField tfTitulo;
    private javax.swing.JTextField tfTombo;
    private javax.swing.JTextField tfVolume;
    private javax.swing.JFormattedTextField tffAnoEdicao;
    // End of variables declaration//GEN-END:variables
}
