/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fvsosp.telas;

import fvsosp.emprestimo.Emprestimo;
import fvsosp.emprestimo.EmprestimoRN;
import fvsosp.emprestimo.EmprestimoTableModel;
import fvsosp.emprestimo.ItensEmprestimoTableModel;
import fvsosp.exemplar.Exemplar;
import fvsosp.exemplar.ExemplarRN;
import fvsosp.leitor.Leitor;
import fvsosp.leitor.LeitorRN;
import fvsosp.leitor.LeitorTableModel;
import fvsosp.usuario.UsuarioRN;
import fvsosp.util.UsuarioAtivo;
import fvsosp.util.Util;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Tulio
 */
public class TelaCadastroEmprestimos extends javax.swing.JDialog {

    Emprestimo emprestimo;
    EmprestimoRN emprestimoRN = new EmprestimoRN();
    Leitor leitor;
    LeitorRN leitorRN = new LeitorRN();
    Set<Exemplar> exemplares = new HashSet<Exemplar>();

    /**
     * Creates new form TelaCadastroEmpr
     */
    public TelaCadastroEmprestimos() {
        initComponents();
        setLocationRelativeTo(null);
        tfDataEmprestimoDia.setText("");
        ExemplarRN exemplarRN = new ExemplarRN();
        setModal(true);
        lblDevolucao.setText("");
//        for (int x = 0; x < exemplarRN.listar().size(); x++) {
//            tbExemplaresEmprestimo.getModel().setValueAt(exemplarRN.listar().get(x), x, 0);
//        }
    }

    public void atualizaTabela() {
        ItensEmprestimoTableModel iETB = new ItensEmprestimoTableModel(exemplares);
        tbExemplaresEmprestimo.setModel(iETB);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        labelEmprestimo = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        tfDataEmprestimoDia = new javax.swing.JFormattedTextField();
        labelDataEmprestimo5 = new javax.swing.JLabel();
        labelDataDevolucao15 = new javax.swing.JLabel();
        tfDataEmprestimoMes = new javax.swing.JFormattedTextField();
        tfDataEmprestimoAno = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tfDataDevolucaoMes = new javax.swing.JFormattedTextField();
        tfDataDevolucaoAno = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        tfDataDevolucaoDia = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        labelDataDevolucao17 = new javax.swing.JLabel();
        RemoveAcr = new javax.swing.JButton();
        labelDataEmprestimo7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbExemplaresEmprestimo = new javax.swing.JTable();
        btNovo5 = new javax.swing.JButton();
        btSair5 = new javax.swing.JButton();
        btSalvar5 = new javax.swing.JButton();
        tfLeitor = new javax.swing.JTextField();
        btPesquisar6 = new javax.swing.JButton();
        tfTombo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblDevolucao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(59, 89, 152));
        jPanel9.setLayout(null);

        labelEmprestimo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        labelEmprestimo.setForeground(new java.awt.Color(255, 255, 255));
        labelEmprestimo.setText("Empréstimo/Devolução");
        jPanel9.add(labelEmprestimo);
        labelEmprestimo.setBounds(0, 0, 340, 30);

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 37));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        tfDataEmprestimoDia.setEditable(false);
        tfDataEmprestimoDia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##"))));
        tfDataEmprestimoDia.setToolTipText("Digite aqui o dia do Empréstimo.");
        tfDataEmprestimoDia.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        labelDataEmprestimo5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelDataEmprestimo5.setText("Data de Empréstimo.:");

        labelDataDevolucao15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelDataDevolucao15.setText("Data de Devolução.:");

        tfDataEmprestimoMes.setEditable(false);
        tfDataEmprestimoMes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##"))));
        tfDataEmprestimoMes.setToolTipText("Digite aqui o mês de Empréstimo.");
        tfDataEmprestimoMes.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        tfDataEmprestimoAno.setEditable(false);
        tfDataEmprestimoAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));
        tfDataEmprestimoAno.setToolTipText("Digite aqui o ano de Empréstimo.");
        tfDataEmprestimoAno.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jLabel21.setText("/");

        jLabel22.setText("/");

        tfDataDevolucaoMes.setEditable(false);
        tfDataDevolucaoMes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##"))));
        tfDataDevolucaoMes.setToolTipText("Digite aqui o mês de Devolução.");
        tfDataDevolucaoMes.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        tfDataDevolucaoAno.setEditable(false);
        tfDataDevolucaoAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));
        tfDataDevolucaoAno.setToolTipText("Digite aqui o ano de Devolução.");
        tfDataDevolucaoAno.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jLabel23.setText("/");

        tfDataDevolucaoDia.setEditable(false);
        tfDataDevolucaoDia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##"))));
        tfDataDevolucaoDia.setToolTipText("Digite aqui o dia de Devolução.");
        tfDataDevolucaoDia.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jLabel24.setText("/");

        labelDataDevolucao17.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelDataDevolucao17.setText("Leitor.:");

        RemoveAcr.setText("Remover");
        RemoveAcr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveAcrActionPerformed(evt);
            }
        });

        labelDataEmprestimo7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelDataEmprestimo7.setText("Tombo.:");

        tbExemplaresEmprestimo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tbExemplaresEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Exemplares do Empréstimo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbExemplaresEmprestimo.setCellSelectionEnabled(true);
        jScrollPane5.setViewportView(tbExemplaresEmprestimo);
        tbExemplaresEmprestimo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        btNovo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fvsosp/imagens/novo_1.png"))); // NOI18N
        btNovo5.setToolTipText("Novo");
        btNovo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovo5ActionPerformed(evt);
            }
        });

        btSair5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fvsosp/imagens/SA.png"))); // NOI18N
        btSair5.setToolTipText("Sair");
        btSair5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSair5ActionPerformed(evt);
            }
        });

        btSalvar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fvsosp/imagens/save_1.png"))); // NOI18N
        btSalvar5.setToolTipText("Salvar");
        btSalvar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvar5ActionPerformed(evt);
            }
        });

        tfLeitor.setEnabled(false);

        btPesquisar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fvsosp/imagens/application-form-magnify-icon.png"))); // NOI18N
        btPesquisar6.setToolTipText("Pesquisar");
        btPesquisar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisar6ActionPerformed(evt);
            }
        });

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblDevolucao.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lblDevolucao.setForeground(new java.awt.Color(255, 0, 0));
        lblDevolucao.setText("jLabel1");
        lblDevolucao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(labelDataEmprestimo5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfDataEmprestimoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfDataEmprestimoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfDataEmprestimoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(labelDataEmprestimo7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfTombo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(RemoveAcr))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                            .addComponent(lblDevolucao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btNovo5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btSalvar5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btSair5))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelDataDevolucao17)
                                .addComponent(tfLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btPesquisar6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(labelDataDevolucao15)
                        .addGap(18, 18, 18)
                        .addComponent(tfDataDevolucaoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDataDevolucaoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDataDevolucaoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfDataEmprestimoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfDataEmprestimoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfDataEmprestimoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21))
                    .addComponent(labelDataEmprestimo5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfDataDevolucaoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfDataDevolucaoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfDataDevolucaoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelDataDevolucao15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(labelDataDevolucao17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btPesquisar6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataEmprestimo7)
                    .addComponent(tfTombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(RemoveAcr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btSair5)
                        .addComponent(btSalvar5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btNovo5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDevolucao))
                .addContainerGap())
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, -1, 340));
        jPanel7.getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovo5ActionPerformed
        limpaCampos();
    }//GEN-LAST:event_btNovo5ActionPerformed

    private void btSair5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSair5ActionPerformed
        dispose();
    }//GEN-LAST:event_btSair5ActionPerformed

    private void btSalvar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvar5ActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja efetuar o seguinte Empréstimo: "
                + "\nData de Empréstimo: " + tfDataEmprestimoDia.getText() + " / " + tfDataEmprestimoMes.getText()
                + " / " + tfDataEmprestimoAno.getText()
                + "\nData de Devolução: " + tfDataDevolucaoDia.getText() + " / " + tfDataDevolucaoMes.getText()
                + " / " + tfDataDevolucaoAno.getText()
                + "\nLeitor: " + tfLeitor.getText()
                + "\nExemplar(es): " + exemplares.toString()) == JOptionPane.YES_OPTION) {

            if (emprestimo == null) {
                emprestimo = new Emprestimo();
            }
            if (Util.chkVazio(tfDataEmprestimoDia.getText(), tfDataEmprestimoMes.getText(), tfDataEmprestimoAno.getText(),
                    tfDataDevolucaoDia.getText(), tfDataDevolucaoMes.getText(), tfDataDevolucaoAno.getText(), tfLeitor.getText())
                    && exemplares.size() > 0) {
                String dataEmprestimo = tfDataEmprestimoDia.getText() + "/" + tfDataEmprestimoMes.getText() + "/" + tfDataEmprestimoAno.getText(),
                        dataDevolucao = tfDataDevolucaoDia.getText() + "/" + tfDataDevolucaoMes.getText() + "/" + tfDataDevolucaoAno.getText();
                try {
                    DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
                    UsuarioRN usuRN = new UsuarioRN();
                    emprestimo.setUsuario(usuRN.pesquisaLogin(UsuarioAtivo.getLogin()));
                    emprestimo.setDataEmprestimo(new Date(fmt.parse(dataEmprestimo).getTime()));
                    emprestimo.setDataDevolucao(new Date(fmt.parse(dataDevolucao).getTime()));
                    emprestimo.setLeitor(leitor);
                    
                    emprestimo.setExemplares(exemplares);
                    
                } catch (ParseException ex) {
                    System.out.println(ex.getMessage());
                }
                int id = emprestimo.getIdEmprestimo();
                if (emprestimoRN.adiciona(emprestimo)) {
                    JOptionPane.showMessageDialog(rootPane, "Empréstimo " + ((id == 0) ? "cadastrado" : "alterado")
                            + " com sucesso!");
                    Iterator<Exemplar> iterator = exemplares.iterator();

                    while (iterator.hasNext()) {
                        Exemplar exemplar = iterator.next();
                        ExemplarRN eRN = new ExemplarRN();
                        exemplar.setSituacao(3);
                        eRN.adiciona(exemplar);
                    }


                    limpaCampos();
                }
            }
        }
    }//GEN-LAST:event_btSalvar5ActionPerformed

    private void btPesquisar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisar6ActionPerformed
        List<Leitor> lista = leitorRN.listar();
        LeitorTableModel itm = new LeitorTableModel(lista);
        Object o = TelaPesquisa.exibeTela(itm, "Leitor");
        if (o != null) {
            Calendar datas = Calendar.getInstance();
            leitor = leitorRN.pesquisarCodigo(Short.parseShort(o.toString()));
            DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
            String data = fmt.format(Calendar.getInstance().getTime()), dia = data.substring(0, 2),
                    mes = data.substring(3, 5), ano = data.substring(6, 10);
            Calendar calendario = new GregorianCalendar(Integer.parseInt(dia), Integer.parseInt(mes),
                    Integer.parseInt(ano));
            calendario.setTime(new Date());
            calendario.add(Calendar.DATE, leitor.getGruposLeitores().getDuracaoDiasEmprestimo());
            tfDataEmprestimoDia.setText(dia);
            tfDataEmprestimoMes.setText(mes);
            tfDataEmprestimoAno.setText(ano);
            String day = fmt.format(calendario.getTime()), mother = day, year = day;
            tfDataDevolucaoDia.setText(day.substring(0, 2));
            tfDataDevolucaoMes.setText(mother.substring(3, 5));
            tfDataDevolucaoAno.setText(year.substring(6, 10));
            tfLeitor.setText(leitor.getNome());
            EmprestimoRN eRN = new EmprestimoRN();
            int qtdLivrosEmprestados = eRN.pesquisarSituacao(leitor, 3);
            if(qtdLivrosEmprestados>0){
               lblDevolucao.setText("Qtd Empréstimos: "+qtdLivrosEmprestados);
            } else {
                lblDevolucao.setText("");
            }
        }
    }//GEN-LAST:event_btPesquisar6ActionPerformed

    private void RemoveAcrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveAcrActionPerformed
        if (tbExemplaresEmprestimo.getSelectedRow() > -1) {
            tbExemplaresEmprestimo.setValueAt("", tbExemplaresEmprestimo.getSelectedRow(), 0);
            exemplares.remove(tbExemplaresEmprestimo.getSelectedRow());
        } else {
            tbExemplaresEmprestimo.setValueAt("", tbExemplaresEmprestimo.getRowCount() - 1, 0);
            exemplares.remove(tbExemplaresEmprestimo.getRowCount() - 1);
        }
    }//GEN-LAST:event_RemoveAcrActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(tfLeitor.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Informe o Leitor!", "OSBiblio", JOptionPane.INFORMATION_MESSAGE);
        } else        
        if (!tfTombo.getText().equals("")) {
            EmprestimoRN empRN = new EmprestimoRN();
            ExemplarRN eRN = new ExemplarRN();
            Exemplar exemplar = eRN.pesquisarTombo(Short.valueOf(tfTombo.getText()));
            if (exemplar != null) {
                if (exemplar.isAtivo() == true) {
                    if ((exemplares.size()+empRN.pesquisarSituacao(leitor, 3))
                            < leitor.getGruposLeitores().getQuantMaxLivros())
                             {
                        if (exemplar.getSituacao()!=3) {
                            exemplares.add(exemplar);
                            atualizaTabela();
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Este Exemplar encontra-se emprestado!", "OSBiblio", JOptionPane.INFORMATION_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Quantidade Máxima \n de Livors Atingida!", "OSBiblio", JOptionPane.INFORMATION_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Exemplar Indisponível!", "OSBiblio", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Exemplar não existe!", "OSBiblio", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Preencha o Tombo!", "OSBiblio", JOptionPane.INFORMATION_MESSAGE);
        }
        tfTombo.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void limpaCampos() {
        emprestimo = null;
        leitor = null;
        exemplares = new HashSet<Exemplar>();
        tfDataEmprestimoDia.setText("");
        tfDataEmprestimoMes.setText("");
        tfDataEmprestimoAno.setText("");
        tfDataDevolucaoDia.setText("");
        tfDataDevolucaoMes.setText("");
        tfDataDevolucaoAno.setText("");
        tfLeitor.setText("");
        atualizaTabela();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastroEmprestimos dialog = new TelaCadastroEmprestimos();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RemoveAcr;
    private javax.swing.JButton btNovo5;
    private javax.swing.JButton btPesquisar6;
    private javax.swing.JButton btSair5;
    private javax.swing.JButton btSalvar5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelDataDevolucao15;
    private javax.swing.JLabel labelDataDevolucao17;
    private javax.swing.JLabel labelDataEmprestimo5;
    private javax.swing.JLabel labelDataEmprestimo7;
    private javax.swing.JLabel labelEmprestimo;
    private javax.swing.JLabel lblDevolucao;
    public javax.swing.JTable tbExemplaresEmprestimo;
    private javax.swing.JFormattedTextField tfDataDevolucaoAno;
    private javax.swing.JFormattedTextField tfDataDevolucaoDia;
    private javax.swing.JFormattedTextField tfDataDevolucaoMes;
    private javax.swing.JFormattedTextField tfDataEmprestimoAno;
    private javax.swing.JFormattedTextField tfDataEmprestimoDia;
    private javax.swing.JFormattedTextField tfDataEmprestimoMes;
    private javax.swing.JTextField tfLeitor;
    private javax.swing.JTextField tfTombo;
    // End of variables declaration//GEN-END:variables
}
