package fvsosp.telas;

import fvsosp.emprestimo.Emprestimo;
import fvsosp.emprestimo.EmprestimoRN;
import fvsosp.leitor.Leitor;
import fvsosp.leitor.LeitorRN;
import fvsosp.acervo.Acervo;
import fvsosp.acervo.AcervoRN;
import fvsosp.emprestimo.EmprestimoTableModel;
import fvsosp.util.Util;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author Tulio
 */
@SuppressWarnings("serial")
public class TelaCadastroEmprestimo extends javax.swing.JDialog {

    Emprestimo emprestimo;
    EmprestimoRN emprestimoRN = new EmprestimoRN();

    /**
     * Creates new form TelaCadastroEmprestimo
     */
    public TelaCadastroEmprestimo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfDataEmprestimoDia = new javax.swing.JFormattedTextField();
        labelDataEmprestimo = new javax.swing.JLabel();
        labelDataDevolucao = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        tfDataEmprestimoMes = new javax.swing.JFormattedTextField();
        tfDataEmprestimoAno = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfDataDevolucaoMes = new javax.swing.JFormattedTextField();
        tfDataDevolucaoAno = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        tfDataDevolucaoDia = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        labelDataDevolucao1 = new javax.swing.JLabel();
        labelDataDevolucao2 = new javax.swing.JLabel();
        cbAcervo = new javax.swing.JComboBox();
        cbLeitor = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        labelEmprestimo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OSBiblio - Empréstimo");
        setModal(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tfDataEmprestimoDia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        tfDataEmprestimoDia.setToolTipText("Digite aqui o dia do Empréstimo.");
        tfDataEmprestimoDia.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        labelDataEmprestimo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelDataEmprestimo.setText("Data de Empréstimo.:");

        labelDataDevolucao.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelDataDevolucao.setText("Data de Devolução.:");

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fvsosp/imagens/save_1.png"))); // NOI18N
        btSalvar.setToolTipText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fvsosp/imagens/remove_1.png"))); // NOI18N
        btRemover.setToolTipText("Excluir");
        btRemover.setEnabled(false);
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fvsosp/imagens/SA.png"))); // NOI18N
        btSair.setToolTipText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fvsosp/imagens/novo_1.png"))); // NOI18N
        btNovo.setToolTipText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fvsosp/imagens/procurar_1.png"))); // NOI18N
        btPesquisar.setToolTipText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        tfDataEmprestimoMes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("##"))));
        tfDataEmprestimoMes.setToolTipText("Digite aqui o mês de Empréstimo.");
        tfDataEmprestimoMes.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        tfDataEmprestimoAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("##"))));
        tfDataEmprestimoAno.setToolTipText("Digite aqui o ano de Empréstimo.");
        tfDataEmprestimoAno.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jLabel1.setText("/");

        jLabel2.setText("/");

        tfDataDevolucaoMes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("##"))));
        tfDataDevolucaoMes.setToolTipText("Digite aqui o mês de Devolução.");
        tfDataDevolucaoMes.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        tfDataDevolucaoAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("##"))));
        tfDataDevolucaoAno.setToolTipText("Digite aqui o ano de Devolução.");
        tfDataDevolucaoAno.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jLabel3.setText("/");

        tfDataDevolucaoDia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("##"))));
        tfDataDevolucaoDia.setToolTipText("Digite aqui o dia de Devolução.");
        tfDataDevolucaoDia.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jLabel4.setText("/");

        labelDataDevolucao1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelDataDevolucao1.setText("Acervo.:");

        labelDataDevolucao2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelDataDevolucao2.setText("Leitor.:");

        cbAcervo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        AcervoRN acvRN = new AcervoRN();         for (Acervo acervo : acvRN.listar()) {             cbAcervo.addItem(acervo);         }

        cbLeitor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        LeitorRN leiRN = new LeitorRN();         for (Leitor leitor : leiRN.listar()) {             cbLeitor.addItem(leitor);         }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDataDevolucao)
                    .addComponent(labelDataEmprestimo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfDataEmprestimoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDataEmprestimoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDataEmprestimoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfDataDevolucaoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDataDevolucaoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSair))
                            .addComponent(tfDataDevolucaoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelDataDevolucao1)
                    .addComponent(labelDataDevolucao2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbLeitor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbAcervo, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDataEmprestimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfDataEmprestimoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfDataEmprestimoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfDataEmprestimoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDataDevolucao)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfDataDevolucaoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfDataDevolucaoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfDataDevolucaoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDataDevolucao1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelDataDevolucao2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSair)
                    .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(59, 89, 152));
        jPanel3.setLayout(null);

        labelEmprestimo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        labelEmprestimo.setForeground(new java.awt.Color(255, 255, 255));
        labelEmprestimo.setText("Empréstimo");
        jPanel3.add(labelEmprestimo);
        labelEmprestimo.setBounds(0, 0, 270, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (emprestimo == null) {
            emprestimo = new Emprestimo();
        }
        if (Util.chkVazio(tfDataEmprestimoDia.getText(), tfDataEmprestimoMes.getText(), tfDataEmprestimoAno.getText(),
                tfDataDevolucaoDia.getText(), tfDataDevolucaoMes.getText(), tfDataDevolucaoAno.getText())
                && cbAcervo.getSelectedIndex() != 0 && cbLeitor.getSelectedIndex() != 0) {
            String dataEmprestimo = tfDataEmprestimoDia.getText() + "/" + tfDataEmprestimoMes.getText() + "/" + tfDataEmprestimoAno.getText(),
                    dataDevolucao = tfDataDevolucaoDia.getText() + "/" + tfDataDevolucaoMes.getText() + "/" + tfDataDevolucaoAno.getText();
            if (dataEmprestimo.replaceAll("/", "").length() < 8 || dataDevolucao.replaceAll("/", "").length() < 8) {
                JOptionPane.showMessageDialog(rootPane, "Preencha os campos no formato dd/mm/aaaa");
            } else {
                try {
                    DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
                    emprestimo.setDataEmprestimo(new Date(fmt.parse(dataEmprestimo).getTime()));
                    emprestimo.setDataDevolucao(new Date(fmt.parse(dataDevolucao).getTime()));
                    Set<Acervo> acr = new HashSet<>();
                    acr.add((Acervo) cbAcervo.getSelectedItem());
                    emprestimo.setAcervos(acr);
                    emprestimo.setLeitor((Leitor) cbLeitor.getSelectedItem());
                } catch (ParseException ex) {
                    System.out.println(ex.getMessage());
                }
            }
            int id = emprestimo.getIdEmprestimo();
            if (emprestimoRN.adiciona(emprestimo)) {
                JOptionPane.showMessageDialog(rootPane, "Empréstimo " + ((id == 0) ? "cadastrado" : "alterado")
                        + " com sucesso!");
                limpaCampos();
            }
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        if (emprestimo != null) {
            if (emprestimo.getIdEmprestimo() != 0) {
                if (JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o Empréstimo do dia " + emprestimo.getIdEmprestimo()
                        + "?", "OSBiblio", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.YES_OPTION) {
                    if (emprestimoRN.remover(emprestimo)) {
                        JOptionPane.showMessageDialog(rootPane, "Empréstimo: " + emprestimo.getIdEmprestimo()
                                + ", excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Não foi possível excluir o empréstimo "
                                + emprestimo.getIdEmprestimo(),
                                "Erro ao Excluir", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
        limpaCampos();
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        limpaCampos();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        List<Emprestimo> lista = new ArrayList<>();
        String dataEmprestimo = tfDataEmprestimoDia.getText() + "/" + tfDataEmprestimoMes.getText() + "/" + tfDataEmprestimoAno.getText(),
                dataDevolucao = tfDataDevolucaoDia.getText() + "/" + tfDataDevolucaoMes.getText() + "/" + tfDataDevolucaoAno.getText();
        DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
        Date emprestimos = null;
        try {
            emprestimos = new Date(fmt.parse(dataEmprestimo).getTime());
        } catch (ParseException ex) {
            System.out.println(ex.getMessage());
        }
        lista = emprestimoRN.listar();
        EmprestimoTableModel itm = new EmprestimoTableModel(lista);
        Object o = TelaPesquisa.exibeTela(itm, "Empréstimo");
        if (o != null) {
            emprestimo = new Emprestimo();
            emprestimo = emprestimoRN.pesquisarCodigo((int) o);
            tfDataEmprestimoDia.setText(emprestimo.getDataEmprestimo().toString().substring(0, 2));
            tfDataEmprestimoMes.setText(emprestimo.getDataEmprestimo().toString().substring(2, 4));
            tfDataEmprestimoAno.setText(emprestimo.getDataEmprestimo().toString().substring(4, 6));
            tfDataDevolucaoDia.setText(emprestimo.getDataDevolucao().toString().substring(0, 2));
            tfDataDevolucaoMes.setText(emprestimo.getDataDevolucao().toString().substring(2, 4));
            tfDataDevolucaoMes.setText(emprestimo.getDataDevolucao().toString().substring(4, 6));
            cbAcervo.setSelectedItem((emprestimo.getAcervos() != null) ? emprestimo.getAcervos() : 0);
            cbLeitor.setSelectedItem((emprestimo.getLeitor() != null) ? emprestimo.getLeitor() : 0);
            btRemover.setEnabled(true);
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    public void limpaCampos() {
        emprestimo = null;
        tfDataEmprestimoDia.setText("");
        tfDataEmprestimoMes.setText("");
        tfDataEmprestimoAno.setText("");
        tfDataDevolucaoDia.setText("");
        tfDataDevolucaoMes.setText("");
        tfDataDevolucaoAno.setText("");
        cbAcervo.setSelectedIndex(0);
        cbLeitor.setSelectedIndex(0);
        tfDataEmprestimoDia.requestFocus();
        btRemover.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastroEmprestimo dialog = new TelaCadastroEmprestimo();
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbAcervo;
    private javax.swing.JComboBox cbLeitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelDataDevolucao;
    private javax.swing.JLabel labelDataDevolucao1;
    private javax.swing.JLabel labelDataDevolucao2;
    private javax.swing.JLabel labelDataEmprestimo;
    private javax.swing.JLabel labelEmprestimo;
    private javax.swing.JFormattedTextField tfDataDevolucaoAno;
    private javax.swing.JFormattedTextField tfDataDevolucaoDia;
    private javax.swing.JFormattedTextField tfDataDevolucaoMes;
    private javax.swing.JFormattedTextField tfDataEmprestimoAno;
    private javax.swing.JFormattedTextField tfDataEmprestimoDia;
    private javax.swing.JFormattedTextField tfDataEmprestimoMes;
    // End of variables declaration//GEN-END:variables
}